server:
  port: 9201

spring:
  application:
    name: consumer-9201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka
  instance:
    instance-id: consumer-9201 # 修改eureka界面的默认描述信息
