server:
  port: 9001

spring:
  application:
    name: provider-9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka
  instance:
    instance-id: provider-9001 # 修改eureka界面的默认描述信息
