#server:
#  port: 9001

spring:
  application:
    name: provider

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://www.man9101:9101/eureka, http://www.man9102:9102/eureka, http://www.man9103:9103/eureka
#  instance:
#    instance-id: provider-9001 # 修改eureka界面的默认描述信息
