server:
  port: 9101

# eureka 服务端配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 表示是否向eureka注册自己
    fetch-registry: false # false表示自己为注册中心
    service-url: # eureka监控页面
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka




